version: '3'

includes:
  ca:
    taskfile: ca/Taskfile.yml
    optional: false
  etcd:
    taskfile: etcd/Taskfile.yml
    optional: false
  esxi65:
    taskfile: esxi65/Taskfile.yml
    optional: false

dotenv: [
  'esxi65/config.conf'
]

vars:
  END: "\e[0m"
  RED: "\e[31m"
  GREEN: "\e[32m"
  BLUE: "\e[34m"
  BOLD:
    sh: tput bold
  ITALIC:
    sh: tput sitm
  UNDERLINE:
    sh: tput smul
  NO_UNDERLINE:
    sh: tput rmul
  STANDOUT:
    sh: tput smso
  NO_STANDOUT:
    sh: tput rmso

tasks:
  default:
    silent: true
    interactive: true
    cmds:
      - task --list

  header:
    desc: "Pretty prints output provided as CLI ARGS as a header"
    silent: true
    aliases:  [ "h2" ]
    vars:
      MESSAGE: '{{.CLI_ARGS}}'
    preconditions:
      - sh: test ! -z "{{.MESSAGE}}"
        msg: "Internal task `header` takes a MESSAGE as parameter. Hint: `task header -- <Header Text>`"
    cmds:
      - echo "{{.RED}}----------{{.BLUE}} {{.MESSAGE}} {{.RED}}----------{{.END}}"

  standout:
    desc: "Pretty prints output provided as CLI ARGS as a standout header"
    silent: true
    aliases: [ "h1" ]
    vars:
      MESSAGE: '{{.CLI_ARGS}}'
    preconditions:
      - sh: test ! -z "{{.MESSAGE}}"
        msg: "Internal task `standout` takes a MESSAGE as parameter. Hint: `task standout -- <Header Text>`"
    cmds:
      - echo "{{.RED}}----------{{.BLUE}}{{.STANDOUT}} {{.MESSAGE}} {{.NO_STANDOUT}}{{.RED}}----------{{.END}}"

  subheader:
    desc: "Pretty prints output provided as CLI ARGS as a header"
    silent: true
    aliases: [ "h3" ]
    vars:
      MESSAGE: '{{.CLI_ARGS}}'
    preconditions:
      - sh: test ! -z "{{.MESSAGE}}"
        msg: "Internal task `subheader` takes a MESSAGE as parameter. Hint: `task subheader -- <Header Text>`"
    cmds:
      - echo "{{.BOLD}}{{.UNDERLINE}}{{.MESSAGE}}{{.END}}"

  important:
    desc: "Pretty prints output provided as CLI ARGS as important output"
    silent: true
    vars:
      MESSAGE: '{{.CLI_ARGS}}'
    preconditions:
      - sh: test ! -z "{{.MESSAGE}}"
        msg: "Internal task `important` takes a MESSAGE as parameter. Hint: `task important -- <Text>"
    cmds:
      - echo "{{.BOLD}}{{.RED}}{{.MESSAGE}}{{.END}}"