version: '3'
vars:
  GITROOT:
    sh: git rev-parse --show-toplevel
  SQLROOT:
    sh: echo $(git rev-parse --show-toplevel)/hosts.sqlite

tasks:

  # Checks

  ck_sqlite:
    desc: "Validates that SQLite CLI is installed"
    silent: true
    internal: true
    preconditions:
      - sh: command -v sqlite
        msg: "SQLite utility required to run this task"

  ck_dbsane:
    desc: "Validates that DB has been initialized"
    silent: true
    internal: true
    preconditions:
      - sh: test -f {{.SQLROOT}}
        msg: "SQLite DB not initialized. Hint: `task hosts:init`"
      - sh: sqlite -list -separator $'\t\t' hosts.sqlite "select * from Hosts;"
        msg: "SQLite DB not initialized. Hint: `rm {{.SQLROOT}}` then `task hosts:init`"

  # Meat and Potatoes

  init:
    desc: "Initializes hosts database"
    silent: true
    deps: [
      ck_sqlite
    ]
    cmds:
      - task h2 -- Initiailzing hosts.sqlite database
      - sqlite {{.GITROOT}}/hosts.sqlite "CREATE TABLE hosts (id integer primary key, module varchar(32), fqdn varchar(256), mac varchar(48))"

  obliterate:
    desc: "Destroys hosts database"
    silent: true
    cmds:
      - task h2 -- Deleting hosts.sqlite database
      - rm {{.SQLROOT}}

  list:
    desc: "Lists hosts currently recorded in el cheapo database"
    silent: true
    deps: [
      ck_sqlite,
      ck_dbsane
    ]
    cmds:
      - sqlite -list -separator $'\t' {{.SQLROOT}} "select * from hosts;"

